name: checkPr

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: "18"

jobs:
  check:
    name: checkPr
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        run: |
          npm install
          npm run build --if-present
